cabal-version:      3.14
name:               cabal-gresource
version:            0.1.0.0
synopsis:           GResource build integration with Cabal
license:            BSD-3-Clause
license-file:       LICENSE
author:             Rafał Kuźnia
maintainer:         rafal.kuznia@protonmail.com
category:           Distribution
build-type:         Simple
extra-doc-files:
    CHANGELOG.md
    README.md
tested-with:        GHC ==9.6.7 || ==9.8.4 || ==9.10.3 || ==9.12.4 || ==9.14.1

common warnings
    ghc-options: -Wall

library
    import:           warnings
    other-modules:    Distribution.Simple.GResource.Custom
                      Distribution.Simple.GResource.Hooks
                      Distribution.Simple.GResource.Internal
    exposed-modules:  Distribution.Simple.GResource
    build-depends:    base >=4.18 && <4.23,
                      Cabal >=3.18 && <3.19,
                      Cabal-hooks >=3.18 && <3.19,
                      filepath >=1.4 && <1.6,
    hs-source-dirs:   src
    default-language: Haskell2010
    default-extensions: DataKinds, OverloadedRecordDot, StaticPointers,
                        DeriveGeneric, DeriveAnyClass
